Repository AY2425S2-CS2103T-T15-1a/tp, pull requests merged in 2025-03, with the labels that each got.

#13 Branch update about us
  docs/AboutUs.md
Labels: type.Task

#22 Branch about us
  docs/AboutUs.md
  docs/images/junixm.png
Labels: type.Task

#28 Update site wide settings
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/package-lock.json
  docs/package.json
Labels: priority.High

#37 Branch add nric field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High, severity.High

#32 Add company.java and rank.java to /exceptions
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/person/Rank.java
  src/test/java/seedu/address/model/person/CompanyTest.java
  src/test/java/seedu/address/model/person/RankTest.java
Labels: type.Task, priority.High, severity.High

#34 Add Duty field to Person
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Duty.java
  src/test/java/seedu/address/model/person/DutyTest.java
Labels: priority.High

#33 Add salary field to person
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Salary.java
  src/test/java/seedu/address/model/person/SalaryTest.java
Labels: type.Task, priority.High

#44 Add method to count number of duties
  src/main/java/seedu/address/model/person/Duty.java
  src/test/java/seedu/address/model/person/DutyTest.java
Labels: priority.High

#48 Branch integrate duty
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Duty.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDuty.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/DutyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High, severity.High

#46 Branch assign duty
  .gitignore
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Duty.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/model/person/DutyTest.java
Labels: priority.High

#52 Branch UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/DutyListPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/images/background.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DutyListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.High, severity.High

#55 Add view command
  src/main/java/seedu/address/logic/commands/exceptions/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Task, priority.High, severity.High

#53 Integrate new fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/model/person/DutyTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#61 Branch unassign duty
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/address/model/person/Duty.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UnassignCommandParserTest.java
  src/test/java/seedu/address/model/person/DutyTest.java
Labels: type.Task, priority.High

#56 Fix minor bug of assign command
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
Labels: type.Bug, priority.Low, severity.Low

#63 Branch fix test
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, priority.High, severity.Low

#68 Branch add picture
  build.gradle
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/placeholder.jpg
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.Medium

#74 Branch filter command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/CompanyContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/CompanyContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Medium

#73 Branch reassign duty
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ReassignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ReassignCommandParser.java
  src/test/java/seedu/address/logic/commands/ReassignCommandTest.java
Labels: type.Enhancement, priority.Medium
