Repository AY2425S2-CS2103T-T15-1a/tp, pull requests merged in 2025-04, with the labels that each got.

#75 Branch uml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EditCommandObjectDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/CompanyContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/CompanyContainsKeywordsPredicateTest.java
Labels: priority.Medium

#94 Fix: Bugs in Assign, Unassign, and Reassign Commands
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ReassignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Duty.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: alpha-bug

#99 Fix filter command bug
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: type.Bug, severity.Low

#84 Add FilterCommand.puml branch
  docs/diagrams/FilterCommand.puml
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/CompanyContainsKeywordsPredicateTest.java
Labels: type.Task

#96 Bug fix find feature
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: alpha-bug

#101 Branch reassign command test
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ReassignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/model/person/Duty.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/ReassignCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#98 Update DG
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/index.md
Labels: type.Task, priority.High, severity.Medium

#106 Fix the verification for checking the same person
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Task, priority.Medium, severity.Medium, alpha-bug

#77 Add ReassignCommand's sequence diagram
  docs/diagrams/ReassignCommandSequenceDiagram.puml
Labels: priority.Medium

#114 Branch add picture
  src/main/java/seedu/address/ui/PersonCard.java
Labels: alpha-bug

#111 Branch reverse order duty list
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ReassignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Duty.java
  src/main/java/seedu/address/storage/JsonAdaptedDuty.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ReassignCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/model/person/DutyTest.java
Labels: alpha-bug

#116 Update alpha user guide
  docs/UserGuide.md
  docs/img.png
Labels: type.Task, priority.High

#113 Highlight person
  docs/diagrams/ReassignCommandSequenceDiagram.puml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ReassignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.VeryLow, alpha-bug

#117 Update DG to include feature implementation UML diagrams
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#122 Update version number in MainApp.java
  src/main/java/seedu/address/MainApp.java
Labels: alpha-bug

#203 Fix use case for deleting a personnel
  docs/DeveloperGuide.md
Labels: DG Bug

#201 Make NRIC error message more comprehensive
  src/main/java/seedu/address/model/person/Nric.java
Labels: priority.High, Feature Bug

#200 Fix application crashing bug
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High, severity.High, Feature Bug

#202 Fix address and phone number validation rule
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: DG Bug, Feature Bug

#205 More DG Fixes
  docs/DeveloperGuide.md
  docs/diagrams/FilterCommand.puml
Labels: priority.High, DG Bug

#214 Update Ui.png
  docs/images/Ui.png
Labels: priority.High
